CTCTRADERS-1090: Add InterchangeControlReference functionality
hmrc/declare-transit-movement-departure-frontend pull request #134
Opened 2020-10-02 14:09 UTC by chris-ianson

2020-10-02 14:59 UTC, alexflav23 requested changes

2020-10-02 14:59 UTC, alexflav23 commented on app/models/XMLWrites.scala
> +  implicit class XMLWritesOps[A](a: A) {
Use a value class here for better runtime performance. 

```scala
 implicit class XMLWritesOps[A](a: A) extends AnyVal {
}
```

2020-10-02 14:59 UTC, alexflav23 commented on it/repositories/MongoSuite.scala
> +      database         <- connection.database(uri.db.get)
Any change we can transform the `.get` to be part of the comprehension? Basically, we can use a monad transformer from cats if that's already in the classpath, or convert the option to a Try manually and do `Future.fromTry`. That way we would get a nice stack trace in event of a failure.

2020-10-05 06:47 UTC, chris-ianson commented on it/repositories/MongoSuite.scala
> +      database         <- connection.database(uri.db.get)
Thanks @alexflav23. I think the parsedUri falls over before we get to the _uri.db.get_ call if the uri structure is invalid and a db name doesn't exist.

2020-10-05 07:35 UTC, alexflav23 approved these changes

2020-10-05 07:36 UTC, merged