CTCTRADERS-1107
hmrc/declare-transit-movement-departure-frontend pull request #150
Opened 2020-10-13 11:50 UTC by kenneth-rayner

Draft PR for Nav. There may be changes as new liability amount page to be implemented with different validation for the alternative route.

2020-10-13 12:01 UTC, garethgooch requested changes

2020-10-13 12:01 UTC, garethgooch commented on app/utils/GuaranteeDetailsCheckYourAnswersHelper.scala
> +        value = Value(lit"••••"),
double check answer isn't passed else where as this will make the field visible, hidden text could have this read out on a screenreader

2020-10-14 06:49 UTC, chris-ianson commented on app/config/FrontendAppConfig.scala
> +  val otherRefMaxLength           = 35
I think in master you have GuaranteeReferenceWithGrn and GuaranteeReferenceWithOther with Constants for length. Call these in your controller rather than having these values repeated in the FrontendAppConfig.

Note: You'll have to add another Constants object in GuaranteeReference object for the 17 value

2020-10-14 06:51 UTC, chris-ianson commented on app/controllers/guaranteeDetails/GuaranteeReferenceController.scala
> +      val lengthGRN = request.userAnswers.get(GuaranteeTypePage) match {
onSubmit and onPageLoad both need to work out grnMaxLength. Can you pull this out into a private method they both share (if it changes, easier to update)

2020-10-14 06:51 UTC, chris-ianson commented on app/controllers/guaranteeDetails/GuaranteeReferenceController.scala
> +      val grnMaxLength = request.userAnswers.get(GuaranteeTypePage) match {
See comment above

2020-10-14 06:52 UTC, chris-ianson commented on app/forms/OtherReferenceFormProvider.scala
> +  val maxLength: Int                  = appConfig.otherRefMaxLength
Call the relevant Constants value (see comment above)

2020-10-14 07:01 UTC, chris-ianson commented on app/utils/GuaranteeDetailsCheckYourAnswersHelper.scala
> +      val displayAmount = answer match {
This might read better as an if checking for _x.trim.nonEmpty_ I know you have the regex so spaces shouldn't be allowed but checking for nonEmpty is easier to read

2020-10-14 07:07 UTC, chris-ianson commented on app/utils/GuaranteeDetailsCheckYourAnswersHelper.scala
> +        value = Value(lit"••••"),
You might want to speak to Adam about accessibility on this field. The requirement is to obscure the data but I'm not sure what a screen reader needs to play back here. Don't think it's a blocker but might have to come back to this.

2020-10-14 07:09 UTC, chris-ianson requested changes
Looks goods, couple of changes. Once this is in might be worthwhile us all going over it. Or handing it off to someone else but going over it as a pair so the person who's acceptance testing understands the behaviour (slightly more involved than other journeys and I'm not sure if it's clearly documented what should happen)

2020-10-14 08:33 UTC, chris-ianson commented on app/controllers/guaranteeDetails/GuaranteeReferenceController.scala
> +    val grnMaxLength = request.userAnswers.get(GuaranteeTypePage) match {
You could remove val and just run the match. Value will return by default.
You could also pass the request.userAnswers.get(GuaranteeTypePage) as the argument (rather than DataRequest[AnyContent])

2020-10-14 08:36 UTC, chris-ianson approved these changes
Looks good. One minot comment on the private method you added if you want to update it. Happy to merge when you're ready.

2020-10-14 08:41 UTC, merged