Ctctraders 1316 nav for document type
hmrc/declare-transit-movement-departure-frontend pull request #299
Opened 2020-11-13 08:49 UTC by kenneth-rayner

2020-11-13 13:41 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +    case DocumentReferencePage(index) => ua => Some(routes.AddExtraDocumentInformationController.onPageLoad(ua.id, index, Index(count(index)(ua)), NormalMode))
Does DocumentReferencePage not need an itemIndex?

2020-11-13 13:43 UTC, chris-ianson requested changes
Couple of comments

2020-11-13 13:43 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +    case DocumentReferencePage(index) => ua => Some(routes.ItemsCheckYourAnswersController.onPageLoad(ua.id, index))
See above

2020-11-13 13:43 UTC, chris-ianson commented on app/pages/addItems/AddExtraDocumentInformationPage.scala
>    override def path: JsPath = JsPath \ toString
This path needs updating so it's saved in the correct place

2020-11-13 13:55 UTC, PSouthern commented on app/pages/addItems/AddExtraDocumentInformationPage.scala
>    override def path: JsPath = JsPath \ toString
> This path needs updating so it's saved in the correct place

@kenneth-rayner , @kevincoatsworth as discussed the url's need to be updated to include the section, e.g. `/:lrn/add-items/:itemIndex/documents/add-documents`, which will impact this too.

2020-11-13 14:21 UTC, kevincoatsworth commented on app/navigation/DocumentNavigator.scala
> +    case DocumentReferencePage(index) => ua => Some(routes.ItemsCheckYourAnswersController.onPageLoad(ua.id, index))
It doesn't have one in the prototype so I guess we've just followed that. Do you think it may require one?

2020-11-13 14:21 UTC, kevincoatsworth commented on app/navigation/DocumentNavigator.scala
> +    case DocumentReferencePage(index) => ua => Some(routes.AddExtraDocumentInformationController.onPageLoad(ua.id, index, Index(count(index)(ua)), NormalMode))
It doesn't have one in the prototype so I guess we've just followed that. Do you think it may require one?

2020-11-13 14:28 UTC, kevincoatsworth commented on app/pages/addItems/AddExtraDocumentInformationPage.scala
>    override def path: JsPath = JsPath \ toString
:+1:

2020-11-16 11:36 UTC, PSouthern requested changes

2020-11-16 11:36 UTC, PSouthern commented on conf/app.routes
>  POST       /:lrn/add-items/:itemIndex/change-add-documents                   controllers.addItems.AddDocumentsController.onSubmit(lrn: LocalReferenceNumber, itemIndex: Index, mode: Mode = CheckMode)
These routes require the `documents` section in the path.  See prototype https://ctc-traders.herokuapp.com/departures/version-5/add-items/documents/add-documents

2020-11-16 13:40 UTC, PSouthern requested changes

2020-11-16 13:40 UTC, PSouthern commented on app/pages/addItems/AddExtraDocumentInformationPage.scala
>    override def path: JsPath = JsPath \ toString
@kevincoatsworth looks like this one has been missed.  Should be `override def path: JsPath = JsPath \ items \ index.position \  documents \ documentIndex.position\ toString` I think

2020-11-16 13:40 UTC, PSouthern commented on test/controllers/addItems/AddDocumentsControllerSpec.scala
> +      redirectLocation(result).value mustEqual s"/common-transit-convention-departure/$lrn/add-items/1/documents/1/document-type"
This should follow the usual pattern for redirectLocation.  The problem is the navigator qualifier, it should be `Document`

```
override def guiceApplicationBuilder(): GuiceApplicationBuilder =
    super
      .guiceApplicationBuilder()
      .overrides(bind(classOf[Navigator]).qualifiedWith(classOf[Document]).toInstance(new FakeNavigator(onwardRoute)))
```

2020-11-16 14:00 UTC, PSouthern approved these changes

2020-11-16 14:14 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +    val documentCount: Int = ua.get(DeriveNumberOfDocuments(index)).getOrElse(0)
You have a private function count which you can call on line 83 to get this _count(index)(ua)_

2020-11-16 14:16 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +    case DocumentTypePage(index, documentIndex) => ua =>  Some(routes.AddAnotherDocumentController.onPageLoad(ua.id, index, CheckMode))
You navigator makes a lot more sense now it has normal and check split out. Minor point but everywhere you specify documentIndex but it's never used, you could replace with an _

2020-11-16 14:17 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +  def addAnotherDocumentRoute(ua:UserAnswers, index:Index, mode:Mode) =
If this isn't used outside DocumentNavigator you could should make it private

2020-11-16 14:18 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +  def addDocumentRoute(ua:UserAnswers, index: Index,  mode:Mode) = {
If this isn't used outside DocumentNavigator you could should make it private

2020-11-16 14:28 UTC, chris-ianson requested changes
Couple of minor comments

2020-11-16 14:28 UTC, chris-ianson commented on app/navigation/DocumentNavigator.scala
> +  def addExtraDocumentInformationRoute(ua:UserAnswers, index:Index, documentIndex:Index, mode:Mode) =
If this isn't used outside DocumentNavigator you could should make it private

2020-11-16 16:35 UTC, chris-ianson approved these changes

2020-11-16 17:03 UTC, merged