CTCTRADERS-1344: add special mentions to itemdetails journey model
hmrc/declare-transit-movement-departure-frontend pull request #321
Opened 2020-11-23 08:45 UTC by ashwinirudrappa

2020-11-23 11:18 UTC, amaalali requested changes
Looks good, the only change around the helper method on the SpecialMention helper method in the Spec

2020-11-23 11:18 UTC, amaalali commented on test/models/journeyDomain/SpecialMentionSpec.scala
> +  }
We should use `unsafeSetVal` to avoid any cleanup being triggered

2020-11-23 11:18 UTC, amaalali commented on app/models/journeyDomain/ItemSection.scala
> +  }
I don't think we need this recover. I don't expect anything here to throw an exception

2020-11-23 11:23 UTC, ashwinirudrappa commented on app/models/journeyDomain/ItemSection.scala
> +  }
@amaalali It was because it was failing the test when there is no node after this fix it was fine.We can talk about

2020-11-23 18:09 UTC, amaalali commented on app/models/journeyDomain/ItemSection.scala
> +  }
I'm not seeing a test, and don't think it's possible to hit this. We use pure functions here with no exception being thrown, so we can remove the recover

2020-11-24 10:27 UTC, amaalali commented on app/models/journeyDomain/ItemSection.scala
> +            DeriveNumberOfSpecialMentions(itemIndex).reader
You should be able to simplify this by using the same technique used with the  DeriveNumberOfSpecialMentions and the filter

```
    AddSpecialMentionPage(itemIndex).reader
      .filter(identity)
      .flatMap {
        _ => DeriveNumberOfSpecialMentions(itemIndex).reader 
```

2020-11-24 12:29 UTC, amaalali approved these changes

2020-11-24 12:43 UTC, merged