CTCTRADERS-1445 U[DATE VALIDATION AND CONTENT FOR CONSIGNEE ADDRESS PAGE
hmrc/declare-transit-movement-departure-frontend pull request #346
Opened 2020-11-25 17:47 UTC by kenneth-rayner

2020-11-26 08:21 UTC, garethgooch commented on test/controllers/addItems/traderSecurityDetails/SecurityConsigneeAddressControllerSpec.scala
> +  private val form         = formProvider(countries, "frank")
??

2020-11-26 08:21 UTC, garethgooch commented on app/forms/addItems/traderSecurityDetails/SecurityConsignorAddressFormProvider.scala
> +            maxLength(35, "securityConsignorAddress.error.AddressLine1.length"),
hardcoded values

2020-11-26 08:21 UTC, garethgooch commented on app/forms/addItems/traderSecurityDetails/SecurityConsigneeAddressFormProvider.scala
> +            maxLength(35, "securityConsigneeAddress.error.AddressLine1.length"),
hardcoded values

2020-11-26 08:21 UTC, garethgooch commented on conf/messages.en
> +securityConsigneeAddress.title = What is the security consignor’s address
consignor in consignee message

2020-11-26 08:21 UTC, garethgooch commented on conf/messages.en
> +securityConsigneeAddress.error.AddressLine1.length = Address line 1 must be 35 characters or less
hard coded value

2020-11-26 08:21 UTC, garethgooch commented on test/controllers/addItems/traderDetails/TraderDetailsConsignorAddressControllerSpec.scala
> +        .set(SecurityConsignorNamePage(index), "ConsignorName")
This looks like the wrong spec file

2020-11-26 08:21 UTC, garethgooch commented on test/controllers/addItems/traderSecurityDetails/SecurityConsigneeAddressControllerSpec.scala
> +      jsonCaptor.getValue must containJson(expectedJson)
contain instead of mustBe?

2020-11-26 08:21 UTC, garethgooch commented on test/controllers/addItems/traderSecurityDetails/SecurityConsignorAddressControllerSpec.scala
> +  private val form         = formProvider(countries, "frank")
???

2020-11-26 08:21 UTC, garethgooch commented on test/controllers/addItems/traderSecurityDetails/SecurityConsigneeAddressControllerSpec.scala
> +      jsonCaptor.getValue must containJson(expectedJson)
contain over mustbe

2020-11-26 08:21 UTC, garethgooch commented on test/forms/addItems/traderSecurityDetails/SecurityConsigneeAddressFormProviderSpec.scala
> +  val consigneeName = "Frank"
??

2020-11-26 08:22 UTC, PSouthern requested changes
Small change required

2020-11-26 08:22 UTC, PSouthern commented on conf/views/addItems/traderSecurityDetails/securityConsigneeAddress.njk
> +                      {{ messages("securityConsignorAddress.heading", consigneeName) }}
Should be `securityConsigneeAddress.heading`

2020-11-30 12:08 UTC, garethgooch approved these changes

2020-11-30 12:10 UTC, merged