CTCTRADERS=2127 amend max number of transit offices, added spec
hmrc/declare-transit-movement-departure-frontend pull request #485
Opened 2021-04-13 10:46 UTC by kenneth-rayner

2021-04-13 10:51 UTC, amaalali requested changes
Hey, we want to add validation on all controllers for this loop so that we enforce the user is adding to a valid index and we should enforce the limit there

2021-04-19 09:51 UTC, MatthewAlexanderBeck commented on app/controllers/actions/TraderDetailsOfficesOfTransitFilter.scala
> +                    request.userAnswers.get(OfficeOfTransitCountryPage(Index(numberOfOffices - 1))) match {
This looks like it may need a refactor as its a bit complicated to read, is there any way we can simplify this or split the logic into readable chunks

2021-04-19 09:51 UTC, MatthewAlexanderBeck commented on app/controllers/actions/TraderDetailsOfficesOfTransitFilter.scala
> +            Future.successful(
Is it possible for these futures to fail? Could we just wrap this whole method in a future successful?

2021-04-19 09:51 UTC, MatthewAlexanderBeck commented on app/controllers/actions/TraderDetailsOfficesOfTransitFilter.scala
> +            println(s"\n\n\n ${index.position} \n\n\n $numberOfOffices \n\n\n")
Println

2021-04-19 09:51 UTC, MatthewAlexanderBeck commented on app/controllers/routeDetails/AddAnotherTransitOfficeController.scala
> +    (identify andThen getData(lrn) andThen requireData andThen officeOfTransitFilter(index, 1)).async {
PageId is hardcoded here, is this correct?

2021-04-19 11:21 UTC, sawan07 commented on app/controllers/routeDetails/AddAnotherTransitOfficeController.scala
> +    (identify andThen getData(lrn) andThen requireData andThen officeOfTransitFilter(index, 1)).async {
It's 0 for OfficeOfTransitCountryController and 1 when it's from this controller. Based on that we will redirect the user to different pages. We can use a boolean instead but we need this value.

2021-04-20 07:09 UTC, kenneth-rayner commented on app/controllers/actions/TraderDetailsOfficesOfTransitFilter.scala
> +                    request.userAnswers.get(OfficeOfTransitCountryPage(Index(numberOfOffices - 1))) match {
Done a refactor

2021-04-20 09:26 UTC, MatthewAlexanderBeck approved these changes

2021-04-20 09:27 UTC, merged