CTCTRADERS-1435 Condition added for checking PreLodged Answer
hmrc/declare-transit-movement-departure-frontend pull request #502
Opened 2021-04-28 15:51 UTC by sawan07

2021-04-29 09:25 UTC, amaalali requested changes
Do we need to update the xml conversion logic for this navigation change or is that already valid?

2021-05-04 17:18 UTC, amaalali reviewed
One small thing that we might be able to refactor

2021-05-04 17:18 UTC, amaalali commented on app/models/journeyDomain/GoodsSummary.scala
> +              } else
It should be possible to refactor these use `filterMandatoryDependent`

2021-05-05 07:33 UTC, sawan07 commented on app/models/journeyDomain/GoodsSummary.scala
> +              } else
Refactored.

2021-05-05 08:55 UTC, amaalali requested changes

2021-05-05 08:55 UTC, amaalali commented on app/models/journeyDomain/GoodsSummary.scala
> +        PreLodgeDeclarationPage.filterMandatoryDependent(_=>false){
I believe this logic is wrong, it will never pass, the condition we want should be something like:

```
PreLodgeDeclarationPage.filterMandatoryDependent(_ == false){
```

2021-05-05 08:55 UTC, amaalali commented on app/models/journeyDomain/GoodsSummary.scala
> +          AddCustomsApprovedLocationPage.filterMandatoryDependent(_=> false){
Similar here

2021-05-05 08:55 UTC, amaalali commented on app/models/journeyDomain/GoodsSummary.scala
> +        PreLodgeDeclarationPage.filterMandatoryDependent(_=>true){
Similar here

2021-05-05 08:55 UTC, amaalali commented on app/models/journeyDomain/GoodsSummary.scala
> +        }
We need to compose together these readers. There are a few that won't be run because they're are not part of the returned reader. The tests should be failing because of this, but if they're not then we have missing test cases

2021-05-06 10:12 UTC, amaalali approved these changes

2021-05-07 09:27 UTC, merged