CTCTRADERS-2385: update carrierAddress njk file legend and fieldset
hmrc/declare-transit-movement-departure-frontend pull request #633
Opened 2021-08-31 08:06 UTC by kenneth-rayner

2021-08-31 08:30 UTC, MatthewAlexanderBeck approved these changes

2021-08-31 10:06 UTC, ericohwotu approved these changes
🧪

2021-09-01 12:56 UTC, jaynabonne approved these changes

2021-09-02 07:52 UTC, vajarova requested changes

2021-09-02 07:52 UTC, vajarova commented on conf/views/declarationType.njk
>            {{ csrf() | safe }}
This isn't following the design pattern
the fileldset should be structured as follows

```
> <form>
> ...
> <fieldset>
> <legend> <h1> </h1> </legend>
> ...any inputs...
> </filedset>
> <button></
> </form>
```

2021-09-02 07:52 UTC, vajarova commented on conf/views/safetyAndSecurity/carrierAddress.njk
>                          errorMessage: form.country.error
This should follow design pattern too see my previous comment

2021-09-02 12:48 UTC, merged