CTCTRADERS-NAV:create seperate navigator for each sections
hmrc/declare-transit-movement-departure-frontend pull request #75
Opened 2020-09-07 09:00 UTC by ashwinirudrappa

2020-09-07 10:44 UTC, amaalali requested changes
There are a few things we can look at: 
- The annotation, can we move those to the navigation package?
- Can we create a single base class / interface?
- Can we adapt the signature of the normalRoutes and checkRouteMap to match what we did in arrivals?
- MainNavigator sounds confusing
- [Optional] Can we use partial application to clean up the noise in the navigators?

2020-09-07 10:44 UTC, amaalali commented on app/navigation/AbstractNavigator.scala
> +  protected def checkRouteMap: Page => UserAnswers => Call
Can we change this to be just `checkRoutes`

2020-09-07 11:06 UTC, ashwinirudrappa commented on app/navigation/MainNavigator.scala
> +class MainNavigator @Inject()() extends AbstractNavigator {
@amaalali Suggest a name please

2020-09-08 09:55 UTC, amaalali approved these changes

2020-09-08 10:24 UTC, merged